name: Build and Commit
on:
    workflow_dispatch:
    push:
        branches:
            - site-internals

jobs:
    build-and-commit:
        name: Build site
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - name: Checkout internals
              uses: actions/checkout@v4.1.1
              with:
                  ref: site-internals
                  path: ./internals
                  fetch-depth: 0

            - name: Install TeX binaries
              # needed for kpsewhich, ideally there's an image where it already
              # exists but...
              run: sudo apt install texlive-binaries

            - name: Build site
              run: |
                  cd $GITHUB_WORKSPACE/internals;
                  npm install --production;
                  npm run build;

            - name: Checkout master
              uses: actions/checkout@v4.1.1
              with:
                  ref: master
                  path: ./master
                  # we only need the current history since this will be a full
                  # replace outside of .github/workflow dir
                  sparse-checkout:

            - name: Copy and commit
              env:
                  GIT_EMAIL: reimu@reimu.ws
                  GIT_NAME: reimu
              run: |
                  # Remove everything except the .github folder which contains
                  # the deploy workflow
                  # mkdir DELETE_THIS
                  # mv $GITHUB_WORKSPACE/master/* DELETE_THIS
                  # mv DELETE_THIS/.github $GITHUB_WORKSPACE/master/
                  # ls -la DELETE_THIS
                  # rm -rf DELETE_THIS
                  rm -rf $GITHUB_WORKSPACE/master/*

                  cp -r $GITHUB_WORKSPACE/internals/built/. $GITHUB_WORKSPACE/master/;

                  cd $GITHUB_WORKSPACE/internals;
                  COMMIT_MESSAGE=$(git log -1 --pretty=%B);
                  cd $GITHUB_WORKSPACE/master;

                  # make at least one change for testing purposes
                  # echo $RANDOM > dirty

                  git config user.email $GIT_EMAIL;
                  git config user.name $GIT_NAME;

                  git add .;
                  git commit -m "$COMMIT_MESSAGE";
                  git push;

            - name: Run Deploy workflow
              env:
                  GITHUB_TOKEN: ${{ secrets.TRIGGER_WORKFLOW_ON_PUSH }}
              run: |
                cd $GITHUB_WORKSPACE/master;
                ls -la
                gh workflow run deploy.yaml -r master
