name: Build and Commit
on:
    workflow_dispatch:
    push:
        branches:
            - site-internals

jobs:
    build-and-commit:
        name: Build site
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Checkout internals
              uses: actions/checkout@v2.3.1
              with:
                  ref: site-internals
                  path: ./internals
                  fetch-depth: 0

            - name: Build site
              run: |
                  cd $GITHUB_WORKSPACE/internals;
                  npm install --production;
                  npm run build;

            - name: Checkout master
              uses: actions/checkout@v2.3.1
              with:
                  ref: master
                  path: ./master

            - name: Copy and commit
              env:
                  GIT_EMAIL: reimu@reimu.ws
                  GIT_NAME: reimu
              run: |
                  rm -rf $GITHUB_WORKSPACE/master/*
                  cp -r $GITHUB_WORKSPACE/internals/built/. $GITHUB_WORKSPACE/master/;

                  cd $GITHUB_WORKSPACE/internals;
                  COMMIT_MESSAGE=$(git log -1 --pretty=%B);
                  cd $GITHUB_WORKSPACE/master;

                  git config user.email $GIT_EMAIL;
                  git config user.name $GIT_NAME;

                  git add .;
                  git commit -m "$COMMIT_MESSAGE";
                  git push;
